export const GET_ERRORS = "ERRORS";

export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_FAVORITES_CURRENT_USER = "SET_FAVORITES_CURRENT_USER";
export const REGISTER_USER = 'REGISTER_USER';

export const SET_LOCATION = "SET_LOCATION";

export const FILTER_LISTINGS = 'FILTER_LISTINGS';
export const LISTINGS_LOADING = 'LISTINGS_LOADING';



